# Generated by Django 3.0.8 on 2020-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='twonums',
            name='num1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twonums',
            name='num2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
