# Generated by Django 3.0.8 on 2020-07-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0003_auto_20200720_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newnums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb1', models.CharField(max_length=200, null=True)),
                ('numb2', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
