# Generated by Django 3.0.8 on 2020-07-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0005_delete_twonums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newnums',
            name='numb1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='newnums',
            name='numb2',
            field=models.FloatField(null=True),
        ),
    ]
