# Generated by Django 3.0.8 on 2020-07-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0008_usercheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinput',
            name='counter',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
