# Generated by Django 3.0.8 on 2020-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0009_apiinput_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinput',
            name='counter',
            field=models.FloatField(default=0),
        ),
    ]
