# Generated by Django 3.0.8 on 2020-07-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0012_auto_20200723_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinput',
            name='repo_count',
            field=models.FloatField(default=0),
        ),
    ]
