# Generated by Django 3.0.8 on 2020-07-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0013_apiinput_repo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinput',
            name='followers_count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apiinput',
            name='following_count',
            field=models.FloatField(default=0),
        ),
    ]
