# Generated by Django 3.0.8 on 2020-07-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0014_auto_20200724_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinput',
            name='counter',
            field=models.FloatField(default=1),
        ),
    ]
