# Generated by Django 3.0.8 on 2020-07-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0015_auto_20200724_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usercheck',
        ),
    ]
