# Generated by Django 3.0.8 on 2020-07-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt1', '0017_auto_20200724_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinput',
            name='repo_count',
            field=models.FloatField(default=0),
        ),
    ]
